name: Fetch and Save Flights

on:
  schedule:
    - cron: '0 6 * * *'  # todos os dias às 6:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API_route_V2_auto.py
      run: python API_route_V2_auto.py
      env:
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        AVIATION_API_KEY: ${{ secrets.AVIATION_API_KEY }}
